image: "ruby:2.4"

before_script:
  - gem install bundler --version 2.1.4 --no-document
  - bundle install --jobs $(nproc)  "${FLAGS[@]}"

build:
  script:
    - bundle exec rake build

spec:
  script:
    - bundle exec rake spec

yard:
  script:
    - bundle exec rake yard

rubocop:
  script:
    - bundle exec rake rubocop
