image: ruby:3.1

stages:
  - build
  - verify
  - test

before_script:
  - gem install bundler --version 2.4.3 --no-document
  - bundle install --jobs $(nproc)  "${FLAGS[@]}"

build:
  stage: build
  script:
    - bundle exec rake build
  artifacts:
    paths:
      - pkg/*.gem

test-31:
  image: ruby:3.1
  stage: test
  needs:
    - yard
    - rubocop
  script:
    - bundle exec rake spec
  artifacts:
    reports:
      junit: test-reports/rspec.xml
      coverage_report:
        coverage_format: cobertura
        path: coverage/coverage.xml
test-32:
  image: ruby:3.2
  stage: test
  needs:
    - yard
    - rubocop
  script:
    - bundle exec rake spec
  artifacts:
    reports:
      junit: test-reports/rspec.xml
      coverage_report:
        coverage_format: cobertura
        path: coverage/coverage.xml

yard:
  stage: verify
  needs:
    - build
  script:
    - bundle exec rake yard

rubocop:
  stage: verify
  needs:
    - build
  script:
    - bundle exec rake rubocop
