image: "ruby:3.1"

stages:
  - build
  - test
  - verify

before_script:
  - gem install bundler --version 2.4.3 --no-document
  - bundle install --jobs $(nproc)  "${FLAGS[@]}"

build:
  stage: build
  script:
    - bundle exec rake build
  artifacts:
    paths:
      - pkg/*.gem

test:
  stage: test
  needs: ["build"]
  script:
    - bundle exec rake spec
  artifacts:
    reports:
      junit: test-reports/rspec.xml

yard:
  stage: verify
  needs: ["build", "test"]
  script:
    - bundle exec rake yard

rubocop:
  stage: verify
  needs: ["build", "test"]
  script:
    - bundle exec rake rubocop
