image: "ruby:2.5"

before_script:
  - gem install bundler --no-document
  - bundle install --jobs $(nproc)  "${FLAGS[@]}"

rspec:
  script:
    - bundle exec rake spec
yard:
  script:
    - bundle exec rake yard

rubocop:
  script:
    - bundle exec rubocop
