image: "ruby:2.4"

stages:
  - build
  - test
  - verify

before_script:
  - gem install bundler --version 2.1.4 --no-document
  - bundle install --jobs $(nproc)  "${FLAGS[@]}"

build:
  script:
    - bundle exec rake build
  artifacts:
    paths:
      - pkg/*.gem

test:
  stage: test
  script:
    - bundle exec rake spec
  artifacts:
    paths:
      - spec/reports/rspec.xml
    reports:
      junit: spec/reports/rspec.xml

verification:
  stage: test
  script:
    - bundle exec rake yard
    - bundle exec rake rubocop
