image: ruby:2.4

pipelines:
  branches:
    master:
      - step:
          name: Build and test current release
          deployment: production
          caches:
            - bundler
          script:
            - gem install bundler
            - bundle config set path './vendor'
            - bundle install
            - bundle exec rake build
            - bundle exec rake yard
            - bundle exec rake rubocop
            - bundle exec rake spec
    develop:
      - step:
          name: Test next release
          deployment: test
          caches:
            - bundler
          script:
            - gem install bundler
            - bundle config set path './vendor'
            - bundle install
            - bundle exec rake yard
            - bundle exec rake rubocop
            - bundle exec rake spec
    release/*:
      - step:
          name: Release preparation
          deployment: staging
          caches:
            - bundler
          script:
            - gem install bundler
            - bundle config set path './vendor'
            - bundle install
            - bundle exec rake yard
            - bundle exec rake rubocop
            - bundle exec rake spec


  default:
    - step:
        name: Default testing
        caches:
          - bundler
        script:
          - gem install bundler
          - bundle config set path './vendor'
          - bundle install
          - bundle exec rake spec

definitions:
  caches:
    bundler: ./vendor
