image: ruby:2.4.0

pipelines:
  default:
    - step:
        name: Ruby 2.3
        image: ruby:2.3
        caches:
          - bundler
        script:
          - ruby --version
          - bundle install --path ./vendor
          - bundle exec rake build
          - bundle exec rake yard
          - bundle exec rake rubocop
          - bundle exec rake spec
    - step:
        name: Ruby 2.4
        image: ruby:2.4
        caches:
          - bundler
        script:
          - ruby --version
          - bundle install --path ./vendor
          - bundle exec rake build
          - bundle exec rake yard
          - bundle exec rake rubocop
          - bundle exec rake spec

definitions:
  caches:
    bundler: ./vendor
