version: 0.2

phases:
  install:
    commands:
      - gem install bundler
  pre_build:
    commands:
      - bundle install
  build:
    commands:
      - bundle exec rake build
      - bundle exec rake yard
      - bundle exec rake rubocop
      - bundle exec rake spec

artifacts:
  files:
    - pkg/*.gem
  discard-paths: yes
  #base-directory: location
