version: 0.2

phases:
  install:
    runtime-versions:
      ruby: 2.4
    commands:
      - gem uninstall bundler --version '<2.1.4'
      - gem install bundler --version 2.1.4
  pre_build:
    commands:
      - bundle install
  build:
    commands:
      - bundle exec rake build
      - bundle exec rake yard
      - bundle exec rake rubocop
      - bundle exec rake spec

artifacts:
  files:
    - pkg/*.gem
  discard-paths: yes
  #base-directory: location
