name: Ruby

on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['2.6', '3.1', '3.2']
    steps:
    - uses: actions/checkout@v3
    # uses: ruby/setup-ruby@0a29871fe2b0200a17a4497bae54fe5df0d973aa # v1.115.3
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: Build
      run: bundle exec rake build
  test:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        ruby-version: ['2.6', '3.1', '3.2']
    steps:
    - uses: actions/checkout@v3
    # uses: ruby/setup-ruby@0a29871fe2b0200a17a4497bae54fe5df0d973aa # v1.115.3
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: Test
      run: bundle exec rake spec
  verify:
    runs-on: ubuntu-latest
    needs: test
    strategy:
      matrix:
        ruby-version: ['3.1']
    steps:
    - uses: actions/checkout@v3
    # uses: ruby/setup-ruby@0a29871fe2b0200a17a4497bae54fe5df0d973aa # v1.115.3
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: Documentation
      run: bundle exec rake yard
    - name: Rubocop
      run: bundle exec rake rubocop
